set(_CATKIN_CURRENT_PACKAGE "finger_sensor")
set(finger_sensor_VERSION "0.0.0")
set(finger_sensor_MAINTAINER "andy <andy@todo.todo>")
set(finger_sensor_PACKAGE_FORMAT "1")
set(finger_sensor_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "rviz_visual_tools" "tf" "tf_conversions" "libpcl-all-dev" "sensor_msgs" "cmake_modules" "baxter_core_msgs" "eigen_conversions")
set(finger_sensor_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs" "rviz_visual_tools" "tf" "tf_conversions" "libpcl-all" "sensor_msgs" "baxter_core_msgs" "eigen_conversions" "pick_and_place")
set(finger_sensor_BUILDTOOL_DEPENDS "catkin")
set(finger_sensor_BUILDTOOL_EXPORT_DEPENDS )
set(finger_sensor_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "rviz_visual_tools" "tf" "tf_conversions" "libpcl-all" "sensor_msgs" "baxter_core_msgs" "eigen_conversions" "pick_and_place")
set(finger_sensor_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "rviz_visual_tools" "tf" "tf_conversions" "libpcl-all" "sensor_msgs" "baxter_core_msgs" "eigen_conversions" "pick_and_place")
set(finger_sensor_TEST_DEPENDS )
set(finger_sensor_DOC_DEPENDS )
set(finger_sensor_DEPRECATED "")