set(_CATKIN_CURRENT_PACKAGE "perception")
set(perception_VERSION "0.0.0")
set(perception_MAINTAINER "rebecca <rebecca@todo.todo>")
set(perception_PACKAGE_FORMAT "1")
set(perception_BUILD_DEPENDS "eigen_conversions" "pcl_ros" "rviz_visual_tools" "std_msgs" "tf")
set(perception_BUILD_EXPORT_DEPENDS "eigen_conversions" "pcl_ros" "rviz_visual_tools" "std_msgs" "tf")
set(perception_BUILDTOOL_DEPENDS "catkin")
set(perception_BUILDTOOL_EXPORT_DEPENDS )
set(perception_EXEC_DEPENDS "eigen_conversions" "pcl_ros" "rviz_visual_tools" "std_msgs" "tf")
set(perception_RUN_DEPENDS "eigen_conversions" "pcl_ros" "rviz_visual_tools" "std_msgs" "tf")
set(perception_TEST_DEPENDS )
set(perception_DOC_DEPENDS )
set(perception_DEPRECATED "")